gematik/spec-ISiK-Basismodul

ImplementationGuide/markdown/ReleaseNotes.md, Resources/fsh-generated/resources/StructureDefinition-ISiKAngehoeriger.json, Resources/fsh-generated/resources/StructureDefinition-ISiKPatient.json, Resources/fsh-generated/resources/StructureDefinition-ISiKVersicherungsverhaeltnisSelbstzahler.json, Resources/input/fsh/ISiKAngehoeriger.fsh, Resources/input/fsh/ISiKPatient.fsh, Resources/input/fsh/ISiKVersicherungsverhaeltnisSelbstzahler.fsh, Resources/sushi-config.yaml, package.json
wait for further commits before merging
=> #88 MS added Str.Stadtteil-PersImGbrf no add need

Resources/fsh-generated/resources/Account-AbrechnungsfallAmbulant.json, Resources/fsh-generated/resources/Encounter-Fachabteilungskontakt.json, Resources/fsh-generated/resources/StructureDefinition-ISiKAngehoeriger.json, Resources/fsh-generated/resources/StructureDefinition-ISiKPatient.json, Resources/fsh-generated/resources/StructureDefinition-ISiKPersonImGesundheitsberuf.json, Resources/fsh-generated/resources/StructureDefinition-ISiKVersicherungsverhaeltnisGesetzlich.json, Resources/fsh-generated/resources/StructureDefinition-ISiKVersicherungsverhaeltnisSelbstzahler.json, Resources/input/fsh/ISiKAbrechnungsfall.fsh, Resources/input/fsh/ISiKAngehoeriger.fsh, Resources/input/fsh/ISiKKontaktGesundheitseinrichtung.fsh, Resources/input/fsh/ISiKPatient.fsh, Resources/input/fsh/ISiKPersonImGesundheitsberuf.fsh, Resources/input/fsh/ISiKVersicherungsverhaeltnisGesetzlich.fsh, Resources/input/fsh/ISiKVersicherungsverhaeltnisSelbstzahler.fsh
Weitere Änderungen und Commits für den Merge der TC_2.0.1 in der Master werden folgen.
=> first commit for TC_2.0.1

ImplementationGuide/ImplementierungsleitfadenIsiK_basismodul.json, ImplementationGuide/markdown/Einfuehrung.md, ImplementationGuide/markdown/ReleaseNotes.md, Resources/sushi-config.yaml, package.json
=> add 2.0.1 version

ImplementationGuide/ImplementierungsleitfadenIsiK_basismodul.json, ImplementationGuide/markdown/ReleaseMatrix.md
ReleaseMatrix für den merge mit Stufe 2.
Nochmal inhaltlich final prüfen vor dem merge.
=> Ig update with release matrix

ImplementationGuide/markdown/Versicherungsverhaeltnis_Beispiele.md
hotfix, da eindeutiger Typo in IG auf simplifier
=> fix: beispiele

ImplementationGuide/markdown/PersonImGesundheitsberuf/PersonImGesundheitsberuf_Profil.md, ImplementationGuide/markdown/Prozedur/Prozedur_Profil.md, ImplementationGuide/markdown/UebergreifendeFestlegungen/UebergreifendeFestlegungen_Suchparameter.md, Resources/input/fsh/ISiKCapabilityStatement.fsh
fixes for IG: Diagnosis and Practitioner
=> fixes basisstufe 2

ImplementationGuide/markdown/UebergreifendeFestlegungen_Suchparameter.md
@jcaumann passt die Formulierung?
=> update: restrict token modifier to certain types

ImplementationGuide/markdown/ReleaseNotes.md, Resources/fsh-generated/resources/StructureDefinition-ISiKVersicherungsverhaeltnisSelbstzahler.json, Resources/input/fsh/ISiKVersicherungsverhaeltnisSelbstzahler.fsh
siehe ticket #179 für hintergrund
=> add: organization as payor

Resources/input/fsh/ISiKBerichtSubSysteme.fsh
Es geht um eine die Änderung der Reference-Types auf generische statt ISiK-spezifische (wie im Ticket vermerkt)
=> update Reference - Kommentierung Stufe 3

Resources/input/fsh/ISiKAbrechnungsfall.fsh
Die grundsätzliche Frage nach MS, würde ich ggf. in einem anderen PR behandeln. 
Dass die Kardinalität falsch war, ist Konsens, @jcaumann.
=> fix cardinality #258

ImplementationGuide/markdown/UebergreifendeFestlegungen/UebergreifendeFestlegungen_Rest.md
Ich habe die Diskussion rund um den tag zur Herkunftskennzeichung für alle Ressourcen für diese Änderung übernommen (nicht nur für Patient), wie [hier](https://github.com/gematik/spec-ISiK-Basismodul/issues/254) vorgebracht. 
Würde dich um Prüfung der Vorgaben (MUSS -> KANN/ SOLLTE) und der weiteren Formulierung bitten, @jcaumann.
Diese Lockerung der Anforderungen sollte vor einer Festlegung in größerer Runde kommuniziert werden.
FYI @markus020 , @alexzautke
=> update provenance constraints

ImplementationGuide/markdown/Abrechnungsfall/Abrechnungsfall_Profil.md, ImplementationGuide/markdown/ReleaseNotes.md
@MaxMTheilig löst ANFISK-129. 
Bitte nicht einfaches merge - wenn überhaupt würde ich squashen.
=> added Account Table 

.github/ISSUE_TEMPLATE/BUG-REPORT.yml, .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md
adds new issue and PR templates
=> issue and pr template

ImplementationGuide/markdown/Diagnose/Diagnose_Profil.md
Link was wrongly pointing to Encoutner
=> fix link Diagnose_Profil.md

ImplementationGuide/markdown/UebergreifendeFestlegungen/Patient_merge.md, ImplementationGuide/markdown/UebergreifendeFestlegungen/Use-Case-Diagram.iuml
Input aus AG aufgenommen
Fortführung Konzept
- Review steht an
=> Update Konzept Patient_merge.md nach AG

Resources/input/fsh/ISiKAngehoeriger.fsh, Resources/input/fsh/ISiKPatient.fsh
bug fix for invariant - for explanation see links in bug ISSUE
=> fix invariant context #330

.github/workflows/main.yml
trigger gh action on every PR
Please go the the `Preview` tab and select the appropriate sub-template:
[**Contributor PR**](?expand=1&template=PR_Template_Contributor.md)
[Version Upgrade **(for Admins)**](?expand=1&template=PR_Template_VersionUpgrade.md)
=> trigger GH actions on every PR

ImplementationGuide/markdown/KontaktGesundheitseinrichtung/Kontakt_Profil.md
Neue Anforderung zum Use Case: Versorgungstellenkontakt geht über den Zeitraum eine Abteilungskontaktes hinaus
Das Szenario ist üblich und sollte daher abgedeckt werden. Bisher keine Festlegung dazu
löst ANFISK-126
Kein Test dazu, soll in 2.AG Basis (und ggf. asynchchron über diesen PR kommentiert werden)
- es handelt es sich nicht um einen Breaking change, da nur "SOLLTE", daher (für diese Stuge) auch nicht zu testen
=> add Requirement ANFISK-126 #328

README.md
=> fix link description

ImplementationGuide/markdown/DecisionLog.md
@MaxMTheilig das war eine Idee von @alexey-tschudnowsky, um in Zukunft relevante Entscheidungen zu dokumentieren. Sollten wir diskutieren.
=> add decision log draft

ImplementationGuide/markdown/UebergreifendeFestlegungen/UebergreifendeFestlegungen_Rest.md
solves https://service.gematik.de/browse/PTDATA-704?filter=16000
=> update HTTP response requirement #308

ImplementationGuide/markdown/Abrechnungsfall/Abrechnungsfall_AnmerkungenZuDenMustSupportFeldern.md
=> update sentence on Account.identifier #245

ImplementationGuide/markdown/UebergreifendeFestlegungen/UebergreifendeFestlegungen_Patient-merge.md, Resources/input/fsh/ISiKPatient.fsh, Resources/input/fsh/patient-merge.fsh
add requirementes and other stuff
=> add ig requirements + comments + examples

ImplementationGuide/markdown/Diagnose/Diagnose_AnmerkungenZuDenMustSupportFeldern.md, ImplementationGuide/markdown/ReleaseNotes.md
=> update encounter type in condition ptdata 879

ImplementationGuide/markdown/ValueSet/ValueSet_Interaktionen.md
Description that informs on UC added - relates to ANFISK-211
=> add UC description

ImplementationGuide/markdown/DecisionLog.md, ImplementationGuide/markdown/ReleaseNotes.md, Resources/fsh-generated/resources/StructureDefinition-ISiKAbrechnungsfall.json, Resources/input/fsh/ISiKAbrechnungsfall.fsh
=> Abrechnungsfall - Fallbezogene Abrechnungsrelevanz von Diagnosen und Prozeduren - ANFISK 206

Resources/fsh-generated/resources/StructureDefinition-ISiKKontaktGesundheitseinrichtung.json, Resources/input/fsh/ISiKKontaktGesundheitseinrichtung.fsh
AFNISK 222
Lediglich informative Änderung (daher als quickfix)
=> add description for rendering issue ANFISK 222

Resources/fsh-generated/resources/Account-AbrechnungsfallDRG.json, Resources/fsh-generated/resources/Encounter-Fachabteilungskontakt.json, Resources/input/fsh/ISiKAbrechnungsfall.fsh, Resources/input/fsh/ISiKKontaktGesundheitseinrichtung.fsh
=> Ptdata 821 account abrechnungsart stufe3

ImplementationGuide/markdown/ReleaseNotes.md
Please go the the `Preview` tab and select the appropriate sub-template:
[**Contributor PR**](?expand=1&template=PR_Template_Contributor.md)
[Version Upgrade **(for Admins)**](?expand=1&template=PR_Template_VersionUpgrade.md)
=> feat: added Releasnotes
